version: "3.8"
services:
  sat-dev:
    container_name: sat-dev
    build: 
      context: .. # Move up to the root to find flake.nix
      dockerfile: docker_dev/Dockerfile
    working_dir: /app # set working directory
    volumes:
      - ../:/app # mount the whole repository into the working directory
    tty: true # don't close container immediatly after creation
